routes/calendar.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
import calendar as cal
from datetime import datetime
from models.datamodels import Car

calendar_bp = Blueprint('calendar', __name__)

@calendar_bp.route('/')
def calendar():

    hungarian_days = ['Hétfő', 'Kedd', 'Szerda', 'Csütörtök', 'Péntek', 'Szombat', 'Vasárnap']
   
    # Alapértelmezett év és hónap az aktuális dátum
    year = request.args.get('year', datetime.now().year, type=int)
    month = request.args.get('month', datetime.now().month, type=int)

    # Naptár adatok lekérdezése az adott évre és hónapra
    month_days = cal.monthrange(year, month)[1]  # Az adott hónap napjainak száma
    days = [(day, hungarian_days[cal.weekday(year, month, day)]) for day in range(1, month_days + 1)]

    cars = Car.query.all()
    
    return render_template('calendar.html', cars=cars, year=year, month=month, days=days, month_names=cal.month_name)

routes/cars.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, current_app, session
from models.datamodels import db, Car
from datetime import datetime
from werkzeug.utils import secure_filename
import os
from form_validators import is_valid_date_format, validate_mileage_is_a_number, validate_licence_plate_is_right_form, is_valid_time_format


cars_bp = Blueprint('cars', __name__, url_prefix='/cars')

types = [
    "ferdehátú",
    "szedán",
    "kombi",
    "dobozos furgon",
    "platós furgon",
    "kisbusz",
    "busz",
    "SUV",
    "pick-up",
    "terepjáró",
    "kisteherautó",
    "nyerges vontató",
    "kisbusz"
]

fuels = [
    "benzin",
    "elektromos",
    "gáz",
    "gázolaj",
    "hidrogén"
]

statuses = [
    "aktív", "inaktív", "foglalható", "törölt"
]

# Engedélyezett fájlkiterjesztések (opcionális)
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

def validate_image(image):
    if not image:
        return "Kérjük, válasszon ki egy képet.", None
    # Ellenőrizzük, hogy a fájl neve tartalmaz-e kiterjesztést
    if '.' not in image.filename:
        return "A fájl neve nem tartalmaz kiterjesztést.", None
    # Ellenőrizzük, hogy a fájl kiterjesztése engedélyezett-e
    extension = image.filename.rsplit('.', 1)[1].lower()
    if extension not in ALLOWED_EXTENSIONS:
        return "Csak PNG, JPG, JPEG vagy GIF formátumú képeket tölthet fel.", None

    # Kép fájlnevének generálása
    filename = f"{datetime.now().strftime('%Y%m%d%H%M%S')}_{secure_filename(image.filename)}"
    upload_folder = current_app.config['UPLOAD_FOLDER']  # Az UPLOAD_FOLDER dinamikus elérése
    filepath = os.path.join(upload_folder, filename)
    
    # Kép mentése
    try:
        image.save(filepath)
        return None, filename
    except Exception as e:
        return f"Hiba történt a kép mentése közben: {e}", None


def check_licence_plate_exists(licence_plate):
    return db.session.query(Car).filter_by(licence_plate=licence_plate).first() is not None

def validate_brand(brand):
    if not brand:
        return "A márka megadása kötelező."
    elif len(brand) > 20:
        return "A márka neve túl hosszú. Legfeljebb 20 karakter lehet."
    return None

def validate_model(model):
    if not model:
        return "Az autó típusának megadása kötelező."
    elif len(model) > 30:
        return "Az autó típusa túl hosszú. Legfeljebb 30 karakter lehet."
    return None

def validate_type(type_):
    if not type_:
        return "Az autó kivitelének megadása kötelező."
    elif type_ not in types:
        return "Érvénytelen kivitel. Kérjük, válasszon a megadott opciók közül."
    return None

def validate_fuel(fuel):
    if not fuel:
        return "Az üzemanyag megadása kötelező."
    elif fuel not in fuels:
        return "Érvénytelen üzemanyag típus. Kérjük, válasszon a megadott opciók közül."
    return None


def validate_status(status):
    if not status:
        return "Az állapot megadása kötelező."
    elif status not in statuses:
        return "Érvénytelen állapot. Kérjük, válasszon a megadott opciók közül."
    return None

def validate_technical_inspection_end_date(date_str):
    if date_str is None:
        return "A műszaki lejárati dátum nem lehet üres."
    try:
        inspection_date = datetime.strptime(date_str, '%Y-%m-%d')
        if inspection_date <= datetime.now():
            return "A műszaki lejárati dátum a jövőben kell legyen."
    except ValueError:
        return "A műszaki lejárati dátum nem érvényes formátum (pl.: 2024-05-01)."
    return None


@cars_bp.route('/add', methods=['GET', 'POST'])
#@role_required('Admin', 'Manager')
#@permission_required('add_car')
def add_car():
    print("elindult")
    if request.method == 'POST':
        print("megvolt a post")
        # Form adatok lekérése
        licence_plate = request.form.get('licence_plate')
        brand = request.form.get('brand')
        model = request.form.get('model')
        type_ = request.form.get('type')
        fuel = request.form.get('fuel')
        mileage = request.form.get('mileage')
        technical_inspection_end_date = request.form.get('technical_inspection_end_date')
        status = request.form.get('status')
        time_stamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S') #request.form.get('time_stamp')
        image_file = request.files.get('image')  # Képfájl kivétele
        
        # Form validáció
        errors = []
        for validator, field_value in [
            (validate_licence_plate_is_right_form, licence_plate),
            (check_licence_plate_exists, licence_plate),
            (validate_brand, brand),
            (validate_model, model),
            (validate_type, type_),
            (validate_fuel, fuel),
            (validate_mileage_is_a_number, mileage),
            (validate_technical_inspection_end_date, technical_inspection_end_date),
            (validate_status, status),
            (is_valid_time_format, time_stamp)
        ]:
            error = validator(field_value)
            if error:
                errors.append(error)
        
        print("request.files tartalma:", request.files)
        # Kép validálása
        image_error, image_path = validate_image(image_file)
        if image_error:
            errors.append(image_error)
        print("validálás lefutott")

        # Hibák kiírása képernyőre
        if errors:
            flash(errors, "warning")
            print("error kiment")
            return render_template('add_car.html', 
                                   types=types, 
                                   fuels=fuels, 
                                   statuses=statuses, 
                                   datetime=datetime,
                                   licence_plate=licence_plate,
                                   brand=brand,
                                   model=model,
                                   type_=type_,
                                   fuel=fuel,
                                   mileage=mileage,
                                   technical_inspection_end_date=technical_inspection_end_date,
                                   status=status
                                  )

        # Új autó objektum létrehozása
        new_car = Car(
            licence_plate=licence_plate,
            brand=brand,
            model=model,
            type=type_,
            fuel=fuel,
            mileage=mileage,
            technical_inspection_end_date=datetime.strptime(technical_inspection_end_date, '%Y-%m-%d'),
            status=status,
            #time_stamp=time_stamp,
            image=image_path
        )

        # Adatbázisba tétel
        try:
            db.session.add(new_car)
            db.session.commit()
            flash("Autó sikeresen hozzáadva a rendszerhez!","success")
            print("Sikeres betétel az adatbázisba")
            return redirect(url_for('cars.add_car'))
        except Exception as e:
            db.session.rollback()
            print(f"Hiba: {e}")  # Nyomtatja a hibát a konzolra
            print("Hiba adatbázisba tételnél")
            flash("Hiba adatbázisba tételnél", "danger")
            #flash({"type": "danger", "message": "Hiba történt az autó mentése közben. Próbálja újra!"}, "danger")
            return render_template('add_car.html', types=types, fuels=fuels, statuses=statuses, datetime=datetime)

    # GET kérés esetén az űrlap renderelése
    return render_template('add_car.html', types=types, fuels=fuels, statuses=statuses, datetime=datetime)

@cars_bp.route('/')
def display_cars():
    cars = Car.query.all()
    image_folder_path = os.path.join(current_app.config['UPLOAD_FOLDER'])
    return render_template('display_cars.html', cars=cars, image_folder_path=image_folder_path)

@cars_bp.route('/edit/<int:car_id>', methods=['GET', 'POST'])
def edit_car(car_id): #nincs kész. nincs tesztelve
    car = Car.query.get_or_404(car_id)
    
    if request.method == 'POST':
        # Form adatok frissítése
        car.brand = request.form['brand']
        car.model = request.form['model']
        car.type = request.form['type']
        car.fuel = request.form['fuel']
        car.mileage = request.form['mileage']
        car.status = request.form['status']
        car.technical_inspection_end_date = request.form['technical_inspection_end_date']
        
        db.session.commit()
        flash("Autó sikeresen frissítve!", "success")
        return redirect(url_for('cars.display_cars'))
    
    return render_template('edit_car.html', car=car)

@cars_bp.route('/remove/<int:car_id>', methods=['POST'])
def remove_car(car_id): #nincs kész. nincs tesztelve
    car = Car.query.get_or_404(car_id)
    car.status = 'removed'
    db.session.commit()
    #flash("Autó eltávolítva!", "danger")
    return redirect(url_for('cars.display_cars'))

@cars_bp.route('/car/<car_licence_plate>')
def display_car(car_licence_plate):
    car = Car.query.filter_by(licence_plate=car_licence_plate).first_or_404()
    return render_template('display_car.html', car=car)

routes/index.py
import os
from flask import Blueprint, current_app, render_template, request, redirect, url_for, flash
from datetime import datetime
from models.datamodels import Car

index_bp = Blueprint('main', __name__)

@index_bp.route('/')
def index():
    cars = Car.query.all()
    image_folder_path = os.path.join(current_app.config['UPLOAD_FOLDER'])
    return render_template('index.html', cars=cars, image_folder_path=image_folder_path)

routes/issuereportings.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from datetime import datetime

issuereportings_bp = Blueprint('issuereportings', __name__)

# Variables:
saved_time = None

@issuereportings_bp.route('/', methods=['GET', 'POST'])
def issuereporting():
    if request.method == 'POST':
        global saved_time
        saved_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Itt kaphatod meg az űrlap adatait
        name = request.form['name']
        license_plate = request.form['license_plate']
        id_code = request.form['id_code']
        message = request.form['message']

        print("Név:", name)
        print("Rendszám:", license_plate)
        print("Személyazonosító kód:", id_code)
        print("Üzenet:", message)
        print("Az űrlap időpontja:", saved_time) 
        
    return render_template('issuereporting.html', saved_time=saved_time)

routes/login.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from datetime import datetime

login_bp = Blueprint('login', __name__)

@login_bp.route('/')
def do_login():
    return render_template('login.html')
    

routes/waybills.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from datetime import datetime
from models.datamodels import db, Waybill
from form_validator_waybills import validate_mileage_is_a_number, validate_licence_plate_is_right_form

waybills_bp = Blueprint('waybills', __name__)

def check_licence_plate_exists(licence_plate):
    return db.session.query(Waybill).filter_by(licence_plate=licence_plate).first() is not None
"""
def check_mileage_is_greater(opening_mileage, licence_plate):
   licence_plate = db.session.get(licence_plate)
   opening_mileage = db.session.
   return licence_plate, opening_mileage
"""
@waybills_bp.route('/', methods=['GET','POST'])
def waybill():
   licence_plate = request.form.get('licence_plate')
   opening_mileage = request.form.get('opening_mileage')
   opening_place = request.form.get('opening_place')
   closeing_mileage = request.form.get('closeing_mileage')
   closeing_location = request.form.get('closeing_location')
   
   if request.method == 'POST':
      errors = []
      for validator, field_value in [
         (validate_licence_plate_is_right_form),
         (validate_mileage_is_a_number),
      ]:
         error = validator(field_value)
         if error:
            errors.append(error)
                
      # Hibák kiírása képernyőre
      if errors:
         flash(errors, "warning")
         print("error kiment")
         return render_template('add_car.html',
                                 licence_plate=licence_plate,
                                 opening_mileage=opening_mileage,
                                 opening_place=opening_place,
                                 closeing_mileage=closeing_mileage,
                                 closeing_location=closeing_location
                                 )

      # Új menetlevél objektum létrehozása
      new_waybill = Waybill(
         licence_plate=licence_plate,
         opening_mileage=opening_mileage,
         opening_place=opening_place,
         closeing_mileage=closeing_mileage,
         closeing_location=closeing_location
      ) 
      # Adatbázisba tétel
      try:
         db.session.add(new_waybill)
         db.session.commit()
         flash("Autó sikeresen hozzáadva a rendszerhez!","success")
         print("Sikeres betétel az adatbázisba")
         return redirect(url_for('cars.add_car'))
      except Exception as e:
         db.session.rollback()
         print(f"Hiba: {e}")  # Nyomtatja a hibát a konzolra
         print("Hiba adatbázisba tételnél")
         flash("Hiba adatbázisba tételnél", "danger")
         #flash({"type": "danger", "message": "Hiba történt az autó mentése közben. Próbálja újra!"}, "danger") 
   return render_template('waybill.html')
 

# @app.route('/contact')
# def contact():
#     return render_template('contact.html')

templates/add_car.html
{% extends "base.html" %}

{% block nav_buttons %}
<li class="nav-item">
    <a class="nav-link" href="{{ url_for('main.index') }}">Kezdőlap</a>
  </li>
<li class="nav-item">
    <a class="nav-link" href="{{ url_for('calendar.calendar') }}">Naptár nézet</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('waybills.waybill') }}">Menetlevél rögzítése</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('issuereportings.issuereporting') }}">Hiba jelentése</a>
  </li> 
{% endblock %}

{% block content %}
<div class="container mt-3 form-container glasseffect">
    <form method="POST" action="{{ url_for('cars.add_car') }}" enctype="multipart/form-data" autocomplete="off">
        <fieldset>
          <legend>Autó hozzáadása a rendszerhez</legend>
          <div class="mb-3">
            <label for="licence_plate" class="form-label">Az autó rendszáma</label>
            <input type="text" class="form-control" name="licence_plate" id="licence_plate" placeholder="pl.: AABB123">
          </div>
          <div class="mb-3">
            <label for="brand" class="form-label">Az autó márkája</label>
            <input type="text" class="form-control" name="brand" id="brand" placeholder="pl.: Volkswagen">
          </div>
          <div class="mb-3">
            <label for="model" class="form-label">Az autó típusa</label>
            <input type="text" class="form-control" name="model" id="model" placeholder="pl.: Golf 1.4 TSI">
          </div>
          <div class="mb-3">
            <label for="type" class="form-label">Kivitel</label>
            <select class="form-select" id="type" name="type">
              {% for type in types %}
                            <option>{{ type }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="mb-3">
            <label for="fuel" class="form-label">Üzemanyag</label>
            <select class="form-select" id="fuel" name="fuel">
              {% for fuel in fuels %}
                            <option>{{ fuel }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="mb-3">
            <label for="mileage" class="form-label">Jelenlegi kilóméter óra állás</label>
            <input type="number" class="form-control" id="mileage" name="mileage">
          </div>
          <div class="mb-3">
            <label for="technical_inspection_end_date" class="form-label">Műszaki lejáratának dátuma</label>
            <input type="date" class="form-control" is="technical_inspection_end_date" name="technical_inspection_end_date">
          </div>
          
          <div class="mb-3">
            <label for="image" class="form-label">Kép az autóról</label>
            <input class="form-control" type="file" id="image" name="image">
          </div>
          <div class="mb-3">
            <label for="status" class="form-label">Státusz</label>
            <select class="form-select" id="status" name="status">
              {% for status in statuses %}
                  <option>{{ status }}</option>
              {% endfor %}
            </select>
          </div>

          <div class="mb-3">
            <label for="time_stamp" class="form-label">Érvényesség kezdete (ma)</label>
            <input type="text" class="form-control" id="time_stamp" name="time_stamp" value="{{ datetime.now().strftime('%Y-%m-%d %H:%M:%S') }}" readonly>
          </div>
          
          <button type="submit" class="btn btn-primary">Rögzítés</button>
        </fieldset>
      </form>
    </div>

{% endblock %}

templates/calendar.html
{% extends "base.html" %}

{% block extra_css %}
  <link rel="stylesheet" href="{{ url_for('static', filename='Styles/calendar.css') }}">
{% endblock %}

{% block title %}Naptár{% endblock %}

{% block nav_buttons %}
<li class="nav-item">
    <a class="nav-link" href="{{ url_for('main.index') }}">Kezdőlap</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('waybills.waybill') }}">Menetlevél rögzítése</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('issuereportings.issuereporting') }}">Hiba jelentése</a>
  </li> 
{% endblock %}

{% block content %}

  <h2 style="text-align: center;">Válassz évet és hónapot</h2>

  <form style="text-align: center;" action="/calendar" method="get">
    <label for="year">Év:</label>
    <select class="btn btn-secondary" name="year" id="year" onchange="this.form.submit()">
        {% for y in range(2020, 2031) %}
            <option value="{{ y }}" {% if y == year %}selected{% endif %}>{{ y }}</option>
        {% endfor %}
    </select>

    <label for="month">Hónap:</label>

    <div class="btn-group">
      <button type="submit" name="month" value="{{ month - 1 if month > 1 else 12 }}" class="btn btn-secondary" {% if month == 1 %}disabled{% endif %}>
        &lt; <!-- Bal nyíl -->
      </button>
      <select class="btn btn-secondary" name="month" id="month" onchange="this.form.submit()">
          {% for m in range(1, 13) %}
              <option value="{{ m }}" {% if m == month %}selected{% endif %}>
                  {{ month_names[m] }}
              </option>
          {% endfor %}
      </select>
      <button type="submit" name="month" value="{{ month + 1 if 12 > month else 1 }}" class="btn btn-secondary" {% if month == 12 %}disabled{% endif %}>
          &gt; <!-- Jobb nyíl -->
      </button>
    </div>
    
  </form>


  <div class="calendar-container">
    <table class="calendar-table">
        <!-- Táblázat fejléc, napok vízszintesen -->
        <thead>
            <tr>
                <th class="fixed-column left">Autók \ Napok</th>
                <!-- Napok (görgethető rész) -->
                {% for day, day_name in days %}
                <th class="scrollable-day">{{ day }}<br>{{ day_name }}</th>
                {% endfor %}

                <th class="fixed-column right">Funkciók</th>
            </tr>
        </thead>

        <!-- Táblázat tartalma, autók -->
        <tbody>
          {% for car in cars %}
            <tr>
                <td class="fixed-column">
                  <a href="{{ url_for('cars.display_car', car_licence_plate=car.licence_plate) }}">
                  {{ car.model }}<h5 id="car-licence-plate">{{ car.licence_plate }}</h5></a></td>
                <!-- Napok (görgethető rész) -->
                {% for day, day_name in days %}
                <td class="scrollable-day"></td>
                {% endfor %}
                <td class="fixed-column right">
                  <button class="btn btn-primary">Foglalás</button>
                  <button class="btn btn-secondary">Menetlevelek</button>
                </td>
            </tr>
          {% endfor %}
        </tbody>
    </table>
  </div>
{% endblock %}

templates/display_car.html
{% extends "base.html" %}

{% block nav_buttons %}
<li class="nav-item">
    <a class="nav-link" href="{{ url_for('main.index') }}">Kezdőlap</a>
  </li>
<li class="nav-item">
    <a class="nav-link" href="{{ url_for('calendar.calendar') }}">Naptár nézet</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('waybills.waybill') }}">Menetlevél rögzítése</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('issuereportings.issuereporting') }}">Hiba jelentése</a>
  </li> 
{% endblock %}

{% block content %}

<div class="container mt-5 car-item-container">
    <h1>Az autó leírása</h1>
    
    <div class="glasseffect car">
        <div class="car-img">
          <img src="{{ url_for('static', filename='uploads/' + (car.image if car.image else 'placeholder.jpg')) }}" alt="Kép az autóról">
        </div>
        <div class="car-buttons">
            <a class="btn btn-primary" href="">Autó foglalása</a>
            <a class="btn btn-primary" href="{{ url_for('waybills.waybill') }}">Menetlevél rögzítése</a>
            <a class="btn btn-secondary" href="">Hiba jelentése</a>
            <a class="btn btn-warning">Autó szerkesztése</a>
            <a class="btn btn-danger">Autó törlése</a>
        </div>
        <div class="car-details">
            <h2 id="car-brand">{{ car.brand }}</h2>
            <h3 id="car-model">{{ car.model }}</h3>
            <p class="card-text"><strong>Rendszám:</strong> {{ car.licence_plate }}</p>
            <p class="card-text"><strong>Üzemanyag:</strong> {{ car.fuel }}</p>
            <p class="card-text"><strong>Kilométeróra állás:</strong> {{ car.mileage }} km</p>
            <p class="card-text"><strong>Státusz:</strong> {{ car.status }}</p>
            <p class="card-text"><strong>Műszaki vizsga lejárat:</strong> {{ car.technical_inspection_end_date }}</p>
        </div>
    </div>
</div>


{% endblock %}

templates/display_cars.html
{% extends "base.html" %}

{% block nav_buttons %}
<li class="nav-item">
    <a class="nav-link" href="{{ url_for('main.index') }}">Kezdőlap</a>
  </li>
<li class="nav-item">
    <a class="nav-link" href="{{ url_for('calendar.calendar') }}">Naptár nézet</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('waybills.waybill') }}">Menetlevél rögzítése</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('issuereportings.issuereporting') }}">Hiba jelentése</a>
  </li> 
{% endblock %}

{% block content %}

<div class="container mt-5 car-item-container">
    <h1>Autók listája</h1>
    
    {% for car in cars %}
    <a href="{{ url_for('cars.display_car', car_licence_plate=car.licence_plate) }}">
    <div class="car-item glasseffect">
        <div class="car-item-left">
          <img src="{{ url_for('static', filename='uploads/' + (car.image if car.image else 'placeholder.jpg')) }}" alt="Kép az autóról">
        </div>
        <div class="car-item-middle">
            <h3 id="car-brand">{{ car.brand }}</h3>
            <h5 id="car-model">{{ car.model }}</h5>
            <h6 id="car-licence-plate">{{ car.licence_plate }}</h6>
        </div>
        <div class="car-item-right">

        </div>
    </div>
    </a>
    {% endfor %}
</div>


{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}Menetlevél rögzítés{% endblock %}

{% block nav_buttons %}
<li class="nav-item">
    <a class="nav-link" href="{{ url_for('calendar.calendar') }}">Naptár nézet</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('waybills.waybill') }}">Menetlevél rögzítése</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('issuereportings.issuereporting') }}">Hiba jelentése</a>
  </li> 
{% endblock %}

{% block content %}
    <h1 class="index_h1">Üdvözlet, a Menetlevél és Flottakezelő rendszerben!</h1>
    <p class="index_p">Választhat a rendelkezésre álló autók közül és rögzítheti a menetleveleit elektronikusan. Foglaljon autót előre, a foglalás menüpontban. Ha valami nincs rendben a gépjárművel, vagy meghibásodást tapasztal, kérjük jelentse a hibát a hiba bejelentő ürlapunkon.</p>

    <div class="car-card-container">
        {% for car in cars %}
        <a href="{{ url_for('cars.display_car', car_licence_plate=car.licence_plate) }}">
            <div class="car-card">
                <img src="{{ url_for('static', filename='uploads/' + (car.image if car.image else 'placeholder.jpg')) }}" alt="Kép az autóról">
                <div class="car-card-body">
                    <div class="car-card-header">
                        <h4 id="car-model">{{ car.brand }}</h4>
                        <h5 id="car-licence-plate">{{ car.licence_plate }}</h5>
                    </div>
                    <div class="car-card-footer">
                        icons {{ url_for('static', filename='uploads/' + (car.image if car.image else 'placeholder.jpg')) }}
                    </div>
                </div>
            </div>
        </a>
        {% endfor %}
          
    </div>
    
{% endblock %}

templates/waybill.html
{% extends "base.html" %}

{% block nav_buttons %}
<li class="nav-item">
    <a class="nav-link" href="{{ url_for('main.index') }}">Kezdőlap</a>
  </li>
<li class="nav-item">
    <a class="nav-link" href="{{ url_for('calendar.calendar') }}">Naptár nézet</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('waybills.waybill') }}">Menetlevél rögzítése</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('issuereportings.issuereporting') }}">Hiba jelentése</a>
  </li> 
  {% endblock %}
{% block content %}
<div class="container mt-3 form-container glasseffect">
  <form method="POST" action="{{ url_for('waybills.waybill') }}" enctype="multipart/form-data" autocomplete="off">
    <fieldset>
      <legend>Menetlevél rögzítése</legend>
      <div class="mb-3">
        <label for="user" class="form-label">Felhasználónév</label>
        <!--Valahogy ide kiiratni a felhasználónevet-->
      </div>
      <div>
        <label for="licence_plate" class="form-label">Az autó rendszáma</label>
        <input type="text" class="form-control" name="licence_plate" id="licence_plate" placeholder="pl.: AABB123">
      </div>
      <div class="mb-3">
        <label for="opening_mileage" class="form-label">Induló km</label>
        <input type="number" class="form-control" id="opening_mileage" name="opening_mileage">
      </div>
      <div class="mb-3">
        <label for="opening_location" class="form-label">Induló hely</label>
        <input type="text" class="form-control" id="opening_location" name="opening_location">
      </div>
      <div class="mb-3">
        <label for="closeing_mileage" class="form-label">Zaró km</label>
        <input type="number" class="form-control" id="closeing_mileage" name="closeing_mileage">
      </div>
      <div class="mb-3">
        <label for="closeing_location" class="form-label">Érkezési hely</label>
        <input type="text" class="form-control" id="closeing_location" name="closeing_location">
      </div>
      <button type="submit" class="btn btn-primary">Mentés</button>
    </fieldset>
  </form>
</div>
{% endblock %}